services:
  
  mysql:
    image: mysql:8
    container_name: campusdbs
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: campusdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - campus-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p123456 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
  
  back:
    build:
      context: .
      dockerfile: Dockerfile
    image: back-end:latest
    container_name: back-container
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/campusdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    volumes:
      - ./logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - campus-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3


networks:
  campus-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  