spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 00000712

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 4MB      # 单个文件最大限制
      max-request-size: 10MB   # 单次请求总大小限制

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

campus:
  jwt:
    secret: yourverylongsecretkeyshouldbeatleast512bytes
    expiration: 86400000 # 3600,000*24s

ai:
  api-key:
  api-secret:
  api-url: https://spark-api-open.xf-yun.com/v1/chat/completions
  model: "lite"
  template:



