name: Android CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 进入真正 Android 项目目录
      - name: Make gradlew executable
        run: chmod +x frontend/campusTask/gradlew

      - name: Run unit tests
        run: |
          cd frontend/campusTask
          ./gradlew test

      - name: Build APK
        run: |
          cd frontend/campusTask
          ./gradlew assembleDebug